---
title: "Datasets"
format: 
  html:
    toc: true

---

## Icebreaker survey

[Download here](https://docs.google.com/spreadsheets/d/e/2PACX-1vRD_PMPFbTkZmIhXcc0y70IEznxMDpaw8tvsD64JvWLT-aogEnMoVjAWTlvLtHiLCUyTRbsA6ePgQnN/pub?gid=1324386097&single=true&output=csv)

## Download the yogurt dataset (Odd number groups)

- [`00_sample_ids_yogurt.csv`](datasets/group_dataset_a/00_sample_ids_yogurt.csv)
- [`01_participant_metadata_yogurt.csv`](datasets/group_dataset_a/01_participant_metadata_yogurt.csv)
- [`02_qpcr_results_yogurt.csv`](datasets/group_dataset_a/02_qpcr_results_yogurt.csv)
- [`03_luminex_results_yogurt.csv`](datasets/group_dataset_a/03_luminex_results_yogurt.csv)

## Download the birth control dataset (Even number groups)

- [`00_sample_ids_period.csv`](datasets/group_dataset_b/00_sample_ids_period.csv)
- [`01_participant_metadata_period.csv`](datasets/group_dataset_b/01_participant_metadata_period.csv)
- [`02_luminex_period.csv`](datasets/group_dataset_b/02_luminex_period.csv)
- [`03_flow_cytometry_period.csv`](datasets/group_dataset_b/03_flow_cytometry_period.csv)
